-- Demo fixtures are managed by Flyway:
-- app/mamxanh-backend/src/main/resources/db/demo/R__demo_sample_data.sql
-- This compatibility file is intentionally inert; Docker Compose no longer executes it.
